version: '2'
services:
    onlinebanking-app:
        image: onlinebanking
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://onlinebanking-mysql:3306/onlinebanking?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    onlinebanking-mysql:
        extends:
            file: mysql.yml
            service: onlinebanking-mysql
